sudo: false
language: python
install: 
    - pip install tox
    - pip install cython
    - make cythonize
script: 
    - tox -v
python:
    - 2.7
env:
    - TOXENV=coveralls DEPENDENCY_INJECTOR_DEBUG_MODE=1
    - TOXENV=pylint
    - TOXENV=flake8
    - TOXENV=pydocstyle
    - TOXENV=py26,py27,py33,py34,py35,pypy,pypy3
