sudo: false
install: 
    - pip install tox
    - pip install cython
    - make cythonize
script: 
    - tox
language: python
python:
    - 3.5
env:
    - TOXENV=coveralls DEPENDENCY_INJECTOR_DEBUG_MODE=1
    - TOXENV=pylint
    - TOXENV=flake8
    - TOXENV=pydocstyle
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
      #    - TOXENV=pypy3
