language: python
python:
  - '2.6'
  - '2.7'
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=coveralls
  - TOXENV=pylint
  - TOXENV=flake8
  - TOXENV=pep257
  - TOXENV=py26
  - TOXENV=py27
