os: linux
dist: xenial
jobs:
  include:
  - python: 3.6
    language: python
    env: TOXENV=coveralls DEPENDENCY_INJECTOR_DEBUG_MODE=1
    install:
      - pip install tox
      - pip install cython
      - make cythonize
    script: tox
  - python: 3.6
    language: python
    env: TOXENV=pylint
    install: pip install tox
    script: tox
  - python: 3.6
    language: python
    env: TOXENV=flake8
    install: pip install tox
    script: tox
  - python: 3.6
    language: python
    env: TOXENV=pydocstyle
    install: pip install tox
    script: tox
  - python: 2.7
    language: python
    env: TOXENV=py27
    install: pip install tox
    script: tox
  - python: 3.4
    language: python
    env: TOXENV=py34
    install: pip install tox
    script: tox
  - python: 3.5
    language: python
    env: TOXENV=py35
    install: pip install tox
    script: tox
  - python: 3.6
    language: python
    env: TOXENV=py36
    install: pip install tox
    script: tox
  - python: 3.7
    language: python
    env: TOXENV=py37
    install: pip install tox
    script: tox
  - python: 3.8
    language: python
    env: TOXENV=py38
    install: pip install tox
    script: tox
  - python: pypy
    language: python
    env: TOXENV=pypy
    install: pip install tox
    script: tox
  - python: pypy3
    language: python
    env: TOXENV=pypy3
    install: pip install tox
    script: tox
notifications:
  slack:
    rooms:
      secure: CdWDgKnfYW7vvvoH3nS3yg3TcNZiYLRUyEp6ukQ4rQiiuR4+ltuvyGyFJWgP8r7VVJ9yHkB0jebCKWLUMsAEt1my33B6eMDEVefovpkdh2eJjGswmm80brt0EJULpgwPOtB1U47Mwca8L5jDW4KSv9RypUFRgn8eHDoWw6LKf5g=
